"""Quotient-switch gates of the BIE backend -- GENERATED by
scripts/experiments/bie_gate_calibration.py from the natural
step-to-step motion of the 25 pre-merge steps of the two BIE
production trajectories (two ellipses 2000-2025, concentric annulus
2000-2025), replayed from the stored states. Never re-fit on a switch
run.

    eps_split        (R_drop)+ floor      : 1.000000e-09  (grid calibration)
    eps_switch_x     |dX|_inf / h_wall    : 3.090179e-03
    eps_switch_theta |dtheta|_inf         : 1.988895e-03
    eps_volume       |dV_merged|/V        : 3.973126e-07  (grid calibration)
"""

QUOTIENT_GATES_BIE = {
    "eps_split": 1e-09,
    "eps_switch_x": 0.0030901786952373237,
    "eps_switch_theta": 0.0019888945394082036,
    "eps_volume": 3.9731261334266935e-07,
}
