"""0L-B2 pre-registered quotient-switch gates -- GENERATED by
scripts/experiments/quotient_switch_calibration.py from the clean
State-II window (B0 cell B, 768/1024), the B1 positive-fixture
shadow switch and the B0 B/D one-step (negative reference).
Never re-fit on a switch run.

    eps_split        (R_drop)+ floor      : 1.000000e-09
    eps_switch_x     |dX|_inf / h_wall    : 1.395735e-02  (separated: False)
    eps_switch_theta |dtheta|_inf         : 3.290518e-05  (separated: True)
    eps_volume       |dV_merged|/V        : 3.973126e-07
"""

QUOTIENT_GATES = {
    "eps_split": 1e-09,
    "eps_switch_x": 0.013957350198870417,
    "eps_switch_theta": 3.290517789275812e-05,
    "eps_volume": 3.9731261334266935e-07,
}
